services:
  web:
    image: odoo:${ODOO_VERSION}
    container_name: ${INSTANCE}
    hostname: ${INSTANCE}
    depends_on:
      - db
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - web-data:/var/lib/odoo
    networks:
      - internal

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${INSTANCE}_db
    hostname: ${INSTANCE}_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  web-data:
  db-data:

networks:
  internal:
