#!/bin/bash

# get script origin path
SCRIPTPATH=$(dirname $0)

echo $SCRIPTPATH

# verify version
if [ $# != 2 ]; then
    echo "USAGE: $0 INSTANCE VERSION" >&2
    exit 1
fi

# intance name is defined as first argument
INSTANCE=$1

# odoo version is defined as second argument
VERSION=$2

# set an error displaying code
set -e

# create a dockers folder on ~/ if it does not exists
if [ ! -d ~/dockers ]; then
    mkdir ~/dockers
    echo "Docker folder created at ~/dockers"
fi

# define instance directory 
INSTANCE_DIR=~/dockers/$INSTANCE


# check if instance directory already exists
if [ -d $INSTANCE_DIR ]; then
    echo "Instance '$INSTANCE' already exists" >&2
    exit 2
fi

# copy recursively from templates folders the necessary items
sudo cp -r $SCRIPTPATH/templates/$VERSION $INSTANCE_DIR

echo "Instance directory created at $INSTANCE_DIR"

# # go to instance directory ~/dockers/$INSTANCE
cd $INSTANCE_DIR


# find . \ # where to start searching for
# -type f \ # specifies the input type is a file
# -exec \ # if the aboves runs correctly, then execute the following command
# # stream editor with subtitute (s/) and global (/g) flag 
# sed -i "s/{instance}/$INSTANCE/g" {} \; # set instance name on all {instance} coincidences

sudo find . -type f -exec sed -i "s/{instance}/$INSTANCE/g" {} \;

echo $SCRIPTPATH

# run instance-up with following instance name
$SCRIPTPATH/instance-up $INSTANCE