#!/bin/bash
SCRIPT=`realpath $0`;
SCRIPTPATH=`dirname $SCRIPT`;
INSTANCE=$1;
set -e;

cd $SCRIPTPATH;
if [ ! -d $HOME/dockers/$INSTANCE ]; then
    echo "INSTANCE '$INSTANCE' does not exists" >&2;
    exit 1;
fi

./instance-down $INSTANCE;
docker volume rm $INSTANCE"_web-data";
docker volume rm $INSTANCE"_db-data";
rm -rf $HOME/dockers/$INSTANCE;
