#!/bin/bash
INSTANCE=$1;
INSTANCE_NEW=$2;
DB=$3;

SCRIPT=`realpath $0`;
SCRIPTPATH=`dirname $SCRIPT`;

set -e;

PROJECTS_DIR=~/dockers
cd $PROJECTS_DIR;

if [ ! -d $INSTANCE ]; then
    echo "Instance '$INSTANCE' does not exist" >&2;
    exit 1;
fi


if [ -d $INSTANCE_NEW ]; then
    echo "Instance '$INSTANCE_NEW' already exist" >&2;
    exit 1;
fi

cp -r $INSTANCE $INSTANCE_NEW

if [ ! -z $DB ]; then
    $SCRIPTPATH/volume-cp $INSTANCE'_web-data' $INSTANCE_NEW'_web-data';
    $SCRIPTPATH/volume-cp $INSTANCE'_db-data' $INSTANCE_NEW'_db-data';
fi

$SCRIPTPATH/instance-rename $INSTANCE_NEW $INSTANCE;
$SCRIPTPATH/instance-up $INSTANCE_NEW;
