#!/bin/bash
# wget https://github.com/efragafd/odoo-instances/tree/server && chmod +x setup && ./setup

set -e;

read -p "Odoo Manager Version: " ODOO_MANAGER_V;
read -p "Domain: " DOMAIN;
read -p "Contact email: " CONTACT;

SCRIPT=`realpath $0`;
SCRIPTPATH=`dirname $SCRIPT`;

if [ -f /etc/debian_version ]; then
    sudo apt update;
    sudo apt install -y \
        rename \
        vim \
        git \
        docker \
        docker-compose \
        zip \
        unzip \
        sudo \
        python3 \
        python3-pip \
    ;
fi

if [ $(basename $(pwd)) != 'odoo-instances' ]; then
    SCRIPTPATH=$SCRIPTPATH/odoo-instances;
    git clone git@github.com:efragafd/odoo-instances.git --single-branch -b server $SCRIPTPATH;
fi

cd $SCRIPTPATH;

# pip3 install --user -r requirements.txt
cd $SCRIPTPATH/templates;

find . -type f -exec sed -i "s/{domain}/$DOMAIN/g" {} \;
find . -type f -exec sed -i "s/{contact}/$CONTACT/g" {} \;

sudo usermod -aG docker $(whoami);

export PATH=$PATH:$SCRIPTPATH;
echo "export PATH=\$PATH:$SCRIPTPATH" >> ~/.profile;

docker network create nginx-proxy;

mkdir -p ~/dockers/nginx;
cp -r $SCRIPTPATH/manager/nginx ~/dockers;
cd ~/dockers/nginx;
docker-compose up -d;
cd -;


mkdir ~/dockers/manager;
echo "VERSION=$ODOO_MANAGER_V" > ~/dockers/manager/config;
echo "DOMAIN=$DOMAIN" >> ~/dockers/manager/config;
chmod +x ~/dockers/manager/config;

instance-new manager master;
cd ~/dockers/manager/instances/master;
find . -type f -exec sed -i "s/manager\.//g" {} \;
cd -;
instance-restart manager master;

cd $SCRIPTPATH;
USER=$(whoami);
sed -i "s:{script_path}:$SCRIPTPATH:g" manager_api.service;
sed -i "s/{user}/$USER/g" manager_api.service;
sudo cp manager_api.service /lib/systemd/system/;
sudo systemctl daemon-reload;
sudo systemctl enable manager_api.service;
sudo systemctl start manager_api.service;