services:
  web:
    image: odoo:14.0
    container_name: {instance}
    hostname: {instance}
    depends_on:
      - db
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    ports:
      - "8069:8069"
      - "8070:8070"
    networks:
      - nginx-proxy
      - internal
  db:
    image: postgres:13.0
    container_name: {instance}_db
    hostname: {instance}_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  web-data:
  db-data:

networks:
  nginx-proxy:
    external: true
  internal:
    external: false


# version: '3.3'
# services:
#   web:
#     image: odoo:13.0
#     restart: unless-stopped
#     container_name: {project}_{instance}
#     hostname: {project}.{instance}
#     depends_on:
#       - db
#     volumes:
#       - web-data:/var/lib/odoo
#       - ./config:/etc/odoo
#       - ./addons:/mnt/extra-addons
#     environment:
#       - VIRTUAL_HOST={instance}.{project}.{domain}
#       - VIRTUAL_PORT=8069
#       - LETSENCRYPT_HOST={instance}.{project}.{domain}
#       - LETSENCRYPT_EMAIL={contact}
#     networks:
#       - nginx-proxy
#       - internal
#   db:
#     image: postgres:11.5
#     container_name: {project}_{instance}_db
#     hostname: {project}.{instance}_db
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_PASSWORD=odoo
#       - POSTGRES_USER=odoo
#       - PGDATA=/var/lib/postgresql/data/pgdata
#     volumes:
#       - db-data:/var/lib/postgresql/data/pgdata
#     networks:
#       - internal

# volumes:
#   web-data:
#   db-data:

# networks:
#   nginx-proxy:
#     external: true
#   internal:
#     external: false
